package com.abhi.it;

import org.springframework.context.annotation.Primary;
import org.springframework.stereotype.Repository;

@Repository("Mysql")
@Primary
public class MySqlDao implements ReportDao{

	@Override
	public void generateReport() {
		// TODO Auto-generated method stub
		System.out.println("Reported generated by sql.....");
	}

}
